name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, test, coverage
        run: |
          npm install
          npm run build
          npm run test:coverage
<<<<<<< HEAD
          npm run coverage
          make test-coverage
        env:
          CI: true
      - name: Coveralls
      - uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }
=======
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
        env:
          CI: true      
>>>>>>> 58d60281f045968da9b062db24b8bae019965283
